version: '2'
services:
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: 'on-failure'

  nginx:
    container_name: nginx
    restart: 'on-failure'
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: 'on-failure'