version: '2'
services:
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: 'on-failure'

  nginx:
    container_name: nginx
    restart: 'on-failure'
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend/certbot/conf:/etc/letsencrypt
      - ./backend/certbot/www:/var/www/certbot

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf 
    restart: 'on-failure'

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./backend/certbot/conf:/etc/letsencrypt
      - ./backend/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email nicholasl.le224@gmail.com -d base.nicholasle.me --agree-tos
