version: '3'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: 'on-failure'
    deploy:
      replicas: 2

  nginx:
    container_name: nginx
    restart: 'on-failure'
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf